### ISSUE TITLE
[BUG] First person view, damage and incorrect amount of items

### ISSUE THREAD

**Issue by JuBooTheBest** [PedroRok/CreateHypertubes#37]
### Description

Forge 1.20.1

1. If you allow first person view from the config, instead of the camera being in the tube it's one block above it.

2. When entering a hypertube in survival you'll take half a heart of suffocation damage.

3. When breaking a hypertube in survival, you'll take back less items than what you initially used to place it, especially in curves.

### Steps to reproduce
FIRST PERSON VIEW

1. Set the "allow first person view" config option to TRUE
2. Enter a hypertube
3. The camera is one block above the tube

DAMAGE

1. Enter a hypertube while in survival mode
2. You take half a heart of suffocation damage

INCORRECT AMOUNT OF ITEMS

1. Get a stack of hypertubes
2. While in survival, build a track containing some curves
3. Break the hypertubes
4. You'll now have less hypertubes than the initial 64

**Comment by PedroRok** [comment]
Thanks for the report! I’ll check this out. The damage issue, btw has already been fixed in commit dc484ee!

**Comment by JuBooTheBest** [comment]
Are you sure it's fixed? I am using the latest version and it still occurs.

**Comment by PedroRok** [comment]
Yeah, the version with the fix isn’t out yet
